In [3]:
import numpy as np
import sys

# 1. Basic Numpy Arrays

In [2]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [3]:
a = np.array([1, 2, 3, 4])

In [4]:
b = np.array([0, .5, 1, 1.5, 2])

In [5]:
a

array([1, 2, 3, 4])

In [6]:
a[0:]

array([1, 2, 3, 4])

In [7]:
a[1:3]

array([2, 3])

In [8]:
a[1:-1]

array([2, 3])

In [9]:
a[::2]

array([1, 3])

In [10]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [11]:
# Multi-index
b[0], b[2], b[-1]

(np.float64(0.0), np.float64(1.0), np.float64(2.0))

# 2. Array Types

In [12]:
a

array([1, 2, 3, 4])

In [13]:
a.dtype

dtype('int64')

In [14]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [15]:
b.dtype

dtype('float64')

In [17]:
np.array([1, 2, 3, 4], dtype=float)     

array([1., 2., 3., 4.])

In [18]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [19]:
c = np.array(['a', 'b', 'c'])

In [20]:
c.dtype

dtype('<U1')

In [24]:
d = np.array([{'a': 1}, sys])

In [26]:
d.dtype

dtype('O')

# 3. Dimensions and shapes

In [27]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [28]:
A.shape

(2, 3)

In [29]:
A.ndim

2

In [30]:
A.size

6

In [31]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [32]:
B.shape

(2, 2, 3)

# 4. Indexing and Slicing of Matrices

In [33]:
# Square matrix
A = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [34]:
A[1]

array([4, 5, 6])

In [35]:
A[1][0]

np.int64(4)

In [36]:
A[1, 0]

np.int64(4)

In [37]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [40]:
A[:3, :3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
A[1] = np.array([10, 10, 10])

In [43]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [44]:
A[2] = 99

In [45]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

# 5. Summary statistics

In [4]:
a = np.array([1, 2, 3, 4])

In [47]:
a.sum()

np.int64(10)

In [49]:
print(a.mean())

2.5


In [5]:
a.std()

np.float64(1.118033988749895)

In [6]:
a.var()

np.float64(1.25)

In [7]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [8]:
A.sum()

np.int64(45)

In [9]:
A.mean()

np.float64(5.0)

In [11]:
A.std() # Standard Deviation

np.float64(2.581988897471611)

In [12]:
# axis=0: tính tổng theo cột (dọc, từ trên xuống).
# axis=1: tính tổng theo hàng (ngang, từ trái qua).
A.sum(axis=0)

array([12, 15, 18])

In [13]:
A.sum(axis=1)

array([ 6, 15, 24])

In [15]:
# axis=0 → tính trung bình theo cột (dọc, gộp tất cả hàng).
# axis=1 → tính trung bình theo hàng (ngang, gộp tất cả cột).
A.mean(axis=0)

array([4., 5., 6.])

In [16]:
A.mean(axis=1)

array([2., 5., 8.])

In [17]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [18]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

# 6. Broadcasting and Vectorized operations

In [19]:
a = np.arange(4)

In [20]:
a

array([0, 1, 2, 3])

In [21]:
a + 10

array([10, 11, 12, 13])

In [22]:
a * 10

array([ 0, 10, 20, 30])

In [23]:
a += 100

In [24]:
a

array([100, 101, 102, 103])

In [25]:
l = [0, 1, 2, 3]

In [26]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [27]:
a

array([100, 101, 102, 103])

In [29]:
b = np.array([10, 10, 10, 10])

In [30]:
a + b

array([110, 111, 112, 113])

# 7. Boolean arrays

In [31]:
a = np.arange(4)

In [32]:
a

array([0, 1, 2, 3])

In [34]:
print(a[0], a[-1])

0 3


In [35]:
a[[True, False, False, True]]

array([0, 3])

In [36]:
a

array([0, 1, 2, 3])

In [37]:
a >= 2

array([False, False,  True,  True])

In [38]:
a[a >= 2]

array([2, 3])

In [39]:
a.mean()

np.float64(1.5)

In [40]:
a[a > a.mean()]

array([2, 3])

In [41]:
a[~(a > a.mean())]

array([0, 1])

In [42]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [43]:
A = np.random.randint(100, size=(3, 3))

In [44]:
A

array([[57,  0, 54],
       [77, 32, 46],
       [68, 32, 55]], dtype=int32)

In [45]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([57, 54, 32, 68, 55], dtype=int32)

In [46]:
A[A > 30]

array([57, 54, 77, 32, 46, 68, 32, 55], dtype=int32)

# 8. Linear Algebra Đại số tuyến tính

In [47]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [48]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [50]:
A.dot(B) #tích vô hướng or nhân ma trận

array([[20, 14],
       [56, 41],
       [92, 68]])

In [51]:
A @ B # Nhân ma trận

array([[20, 14],
       [56, 41],
       [92, 68]])

In [53]:
B.T # Nhân nghịch đảo

array([[6, 4, 2],
       [5, 3, 1]])

# 9. Size of objects in Memory

## Int, floats

In [54]:
# An integer in Python is > 24bytes
sys.getsizeof(1)

28

In [55]:
# Longs are even larger
sys.getsizeof(10**100)

72

In [57]:
# Numpy size is much smaller
np.dtype(int).itemsize

8

In [58]:
# Numpy size is much smaller
np.dtype(np.int8).itemsize

1

In [59]:
np.dtype(float).itemsize

8

## Lists are even larger

In [60]:
# A one-element list
sys.getsizeof([1])

64

In [61]:
# An array of one element in numpy
np.array([1]).nbytes

8

## And performance is also important

In [62]:
l = list(range(100000))

In [63]:
a = np.arange(100000)

In [65]:
%time np.sum(a ** 2)# Đo thời gian chạy một dòng lệnh

CPU times: total: 0 ns
Wall time: 0 ns


np.int64(333328333350000)

In [66]:
%time sum([x ** 2 for x in l])

CPU times: total: 15.6 ms
Wall time: 18.6 ms


333328333350000

# 10. Useful Numpy functions

## random

In [67]:
np.random.random(size=2)

array([0.19420203, 0.96477926])

In [68]:
np.random.normal(size=2)

array([-0.2903463 ,  2.05906377])

In [69]:
np.random.rand(2, 4)

array([[0.6782094 , 0.28738137, 0.60018748, 0.45003391],
       [0.24154084, 0.64754068, 0.74984827, 0.28746858]])

## arange

In [70]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [71]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

## linspace

In [72]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [73]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [74]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## zeros, ones, empty

In [75]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [76]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [77]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [78]:
np.empty((2, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

## identity and eye
### identity: Tạo ma trận đơn vị kích thước n × n.
### np.eye(N, M=None, k=0)

In [79]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [80]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [81]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [82]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [83]:
np.eye(8, 4, k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [84]:
"Hello World"[6]

'W'