In [25]:
import numpy as np
import sys

# 1. Basic Numpy Arrays

In [2]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [3]:
a = np.array([1, 2, 3, 4])

In [4]:
b = np.array([0, .5, 1, 1.5, 2])

In [5]:
a

array([1, 2, 3, 4])

In [6]:
a[0:]

array([1, 2, 3, 4])

In [7]:
a[1:3]

array([2, 3])

In [8]:
a[1:-1]

array([2, 3])

In [9]:
a[::2]

array([1, 3])

In [10]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [11]:
# Multi-index
b[0], b[2], b[-1]

(np.float64(0.0), np.float64(1.0), np.float64(2.0))

# 2. Array Types

In [12]:
a

array([1, 2, 3, 4])

In [13]:
a.dtype

dtype('int64')

In [14]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [15]:
b.dtype

dtype('float64')

In [17]:
np.array([1, 2, 3, 4], dtype=float)     

array([1., 2., 3., 4.])

In [18]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [19]:
c = np.array(['a', 'b', 'c'])

In [20]:
c.dtype

dtype('<U1')

In [24]:
d = np.array([{'a': 1}, sys])

In [26]:
d.dtype

dtype('O')

# 3. Dimensions and shapes

In [27]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [28]:
A.shape

(2, 3)

In [29]:
A.ndim

2

In [30]:
A.size

6

In [31]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [32]:
B.shape

(2, 2, 3)

# 4. Indexing and Slicing of Matrices

In [33]:
# Square matrix
A = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [34]:
A[1]

array([4, 5, 6])

In [35]:
A[1][0]

np.int64(4)

In [36]:
A[1, 0]

np.int64(4)

In [37]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [40]:
A[:3, :3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
A[1] = np.array([10, 10, 10])

In [43]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [44]:
A[2] = 99

In [45]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

# 5. Summary statistics

In [46]:
a = np.array([1, 2, 3, 4])

In [47]:
a.sum()

np.int64(10)

In [49]:
print(a.mean())

2.5
